//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WhiteCloudHomestayManagementSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Invoice
    {
        public int InvoiceId { get; set; }
        public Nullable<System.Guid> ReservationId { get; set; }
        public Nullable<int> StatusId { get; set; }
        public System.DateTime IssuedDate { get; set; }
        public Nullable<System.DateTime> CheckOutDate { get; set; }
        public decimal HomestayCharge { get; set; }
        public Nullable<decimal> ServiceCharge { get; set; }
        public Nullable<decimal> Surcharge { get; set; }
        public decimal TotalAmount { get; set; }
    
        public virtual Reservation Reservation { get; set; }
        public virtual InvoiceStatus InvoiceStatus { get; set; }
    }
}
