//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WhiteCloudHomestayManagementSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Invoice
    {
        public int InvoiceID { get; set; }
        public Nullable<int> BookingID { get; set; }
        public Nullable<decimal> Amount { get; set; }
        public string Status { get; set; }
        public System.DateTime IssuedDate { get; set; }
    
        public virtual Booking Booking { get; set; }
    }
}
