//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WhiteCloudHomestayManagementSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Payment
    {
        public int PaymentId { get; set; }
        public Nullable<System.Guid> ReservationId { get; set; }
        public decimal Amount { get; set; }
        public string Status { get; set; }
        public System.DateTime IssuedDate { get; set; }
        public Nullable<int> PaymentTypeId { get; set; }
    
        public virtual PaymentType PaymentType { get; set; }
        public virtual Reservation Reservation { get; set; }
    }
}
